# This is a basic workflow to help you get started with Actions

name: Upload Element to the gh-pages branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - uses: robinraju/release-downloader@v1.8
        with: 
          # The source repository path.
          # Expected format {owner}/{repo}
          # Default: ${{ github.repository }}
          repository: "vector-im/element-web"
          tag: "v1.11.46"
          fileName: "element-v1.11.46.tar.gz"
          extract: true

      - name: Delete the production directory if it already exists
        run: if [ -d production ]; then rm -rf production; fi

      - name: Rename the element build directory to production
        run: mv element-v1.11.46 production

      - name: Copy the element config
        run: cp config.json production

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'production'
          default_author: github_actor
          fetch: false
          message: 'Upload Element'
